version: '3.8'

services:
  hive_app:
    container_name: hive_app
    build:
      context: .
      args:
        REACT_APP_API_BACKED_URL: "http://vllm-backend:8000"
      dockerfile: Dockerfile.ui
    ports:
      - "80:80"

  vllm-backend:
    container_name: hive_backend
    image: vllm/vllm-openai:latest
    ports:
      - "8000:8000"
    ipc: "host"
    command: --model # Define your model here, and any additional volumes or commands. See vLLM for reference.
